CHANGES.md
space_packet_parser/parser.py

Shows up when filling our BitStream ring buffer for reading large binary files in chunks. Previously, += added new data to the buffer but left the cursor (pos) in place. New behavior moves the cursor to the end of the BitStream. This fix forces that cursor to stay put when filling the ring buffer.

Fix compatibility with new BitStream 

---

.github/workflows/tests.yml
pyproject.toml

This allows installation with Python 3.12+ and newer versions of bitstring as well.
homepage also must be a uri and not an empty string, so I added that in.

Remove upper pin restriction on the package

---

.github/CODEOWNERS
.github/pull_request_template.md
.gitignore
docs/source/developers.md

Add .venv to .gitignore
Add a CODEOWNERS file to automate adding PR reviewers
Update PR guidelines and release documentation

Update PR and Release Docs

---

.github/pull_request_template.md
CITATION.cff
docs/source/changelog.md
docs/source/users.md
examples/parsing_and_plotting_idex_waveforms_from_socket.py
space_packet_parser/parser.py
space_packet_parser/xtcedef.py
tests/integration/test_xtce_based_parsing/test_jpss_parsing.py
tests/test_data/test_xtce.xml
tests/unit/test_parser.py
tests/unit/test_xtcedef.py

Feature request to parse the short and long descriptions of Parameter objects. I also added a pretty comprehensive parsing test for a full XTCE document and changed Parameter and SequenceContainer to inherit from AttrComparable so we can assert on the resulting parsed objects.

Parsing Parameter Short and Long Descriptions

---

.github/workflows/run-pylint.yml
.github/workflows/test-python-version.yml
.github/workflows/tests.yml
Dockerfile

Change the default python version for our tests to Python 3.11 (overridden with BASE_IMAGE_PYTHON_VERSION)
Brief description of changes. If you write good commit messages, put the concatenated list of messages here.

Add run-pylint.yml Action to lint code on all pushes and PRs

---

docs/source/changelog.md
space_packet_parser/parser.py

This uses bytes objects directly in the buffers. Keeping track of the current position manually. Currently, this provides a modest speedup for full packet parsing because we still create a new ConstBitStream for each packet parsing. But for `ccsds_header_only=True` we get a 10x speedup.
I'm opening this as a draft for now to aid discussion.
The other thing that helped with the speed here is defaulting to a full read of a file rather than `file.read(4096)` as it was before and creating lots of small appends to the bytes buffer. Happy to remove this if you'd prefer people to input -1 manually to get that, but figured it is likely what people would want (may be wrong there).
closes #33
- [n/a] Deprecated/superseded code is removed or marked with deprecation warning
- [n/a] Current …

PERF: Use bytes objects for the buffer rather than bitstring

---

.github/workflows/run-pylint.yml
CITATION.cff
docker-compose.yml
docs/source/changelog.md
pyproject.toml

Bump version in pyproject.toml and CITATION.cff
Mark 4.2.0 as released in preparation
Minor changelog updates
Add target option to docker-compose for local testing Add lint service in docker-compose for local linting

Fast forward 4.2.0 release changes back to main

---

docs/source/xtce_variable_length_packets.md

Created an explanation and example for how to work with variable length packets in xtce. 
- [N/A] The changelog.md has been updated

Add example of variable length field calculations to documentation

---

space_packet_parser/parser.py
space_packet_parser/xtcedef.py
tests/unit/test_xtcedef.py

Avoid bitstring and do the bitwise reading and manipulations ourselves with bitwise logic. This greatly increases the performance of the parser by ~3-5x in the read routine. This is sort of the MVP for speed-ups by just implementing the routines we need and trying to replicate bitstring. We could do better by refactoring the `_get_format_string()` logic and avoiding any string matching/parsing/splitting too.
I did not fully remove bitstring at this point since there is a lot of logic surrounding it in `parser.py`. We could make it an optional dependency, but it would be nice to get rid of the `legacy_parse_packet()` method if we go that route. Happy to add that deprecation path here if it'd be useful, but probably a major version bump then.
**main**
**this branch**
- [n/a] New …

ENH: Change parsing logic to bytes manipulation directly

---

docs/source/changelog.md
space_packet_parser/xtcedef.py
tests/unit/test_xtcedef.py

If an entry has duplicate labels for different raw values we need to lookup based on values rather than labels. The values are the unique piece of the enumeration, so swap the dictionary key/value storage.
- [n/a] Deprecated/superseded code is removed or marked with deprecation warning
- [n/a] Current dependencies have been properly specified and old dependencies removed

FIX: Enumerated parameter lookup of duplicate labels

---

space_packet_parser/xtcedef.py

We can get the dunder attribute for comparison which is faster than calling eval on the expression. Also clean up some of the uses of `.values()` in the comparisons.
Goes from 1.25s in my test case to about 0.25s.
**main**
**this branch**
- [n/a] Deprecated/superseded code is removed or marked with deprecation warning
- [n/a] Current dependencies have been properly specified and old dependencies removed
- [n/a] New code/functionality has accompanying tests and any old tests have been updated to match any new assumptions
- [n/a] The changelog.md has been updated

MNT: Use direct operator evaluation rather than eval()

---

docs/source/changelog.md
space_packet_parser/xtcedef.py
tests/conftest.py
tests/test_data/test_xtce.xml
tests/unit/test_xtcedef.py

- Add error handling for unknown and invalid parameter type element during XTCE parsing

Add error handling for invalid/unknown parameter type

---

space_packet_parser/xtcedef.py
tests/unit/test_parser.py
tests/unit/test_xtcedef.py

These tests were passing because the input data was a ConstBitStream which is still handled (until we rip it all out) so we weren't really testing the PacketData object's ability to parse data. 
- Update StringDataEncoding tests to use PacketData instead of ConstBitStream
- Add some more type-hinting throughout xtcedef.py
- Update unit tests for integer parsing using PacketData instead of ConstBitStream 
- Update float encoding unit tests to use PacketData 
- Update enumerated parameter type tests to use PacketData 
- Update binary parameter parsing test to use PacketData 
- Update boolean parameter parsing tests to use PacketData 
- Update time parameter type parsing tests to use PacketData instead of ConstBitStream

Fix Unit Tests Relying on ConstBitStream to use PacketData Instead

---

.github/workflows/test-python-version.yml
.github/workflows/tests.yml
Dockerfile
docker-compose.yml
docs/source/changelog.md
examples/parsing_and_plotting_idex_waveforms_from_socket.py
pyproject.toml
space_packet_parser/parser.py
tests/integration/test_bufferedreader_parsing.py
tests/integration/test_csv_based_parsing/test_ctim_parsing.py
tests/integration/test_socket_parsing.py
tests/integration/test_xtce_based_parsing/test_inheritance_restrictions.py
tests/integration/test_xtce_based_parsing/test_suda_parsing.py
tests/unit/test_csvdef.py

This removes the bitstring dependency and all bitstring inputs allowed with it. You can pass in the raw objects instead of the bitstring objects now.
~~This also removes the `legacy_parser` method which was kept around to support csv parsing. This has been removed in favor of converting the csv packet definitions into the XTCE format instead.~~
This sits on top of https://github.com/medley56/space_packet_parser/pull/58 so there wasn't as much thrashing going on. Only the second commit is the removal portion.
~~NOTE: I have removed the entire csvdef module. I am not sure if you want to keep that around or not. This is definitely the heavy-handed approach of just removing all of the legacy things and moving on in a major version bump.~~

Remove bitstring dependency

---

.github/workflows/run-pycodestyle.yml
.gitignore
Dockerfile
docker-compose.yml
pycodestyle.ini
pyproject.toml
space_packet_parser/csvdef.py
space_packet_parser/xtcedef.py

- Add pycodestyle.ini custom config file (must be manually referenced with pycodestyle CLI) 
- Add github workflow to check pycodestyle (in Docker) 
- Add style target in Dockerfile and style service in docker-compose.yml 
- Fix the issues caught by pycodestyle

Add pycodestyle as dev dependency

---

pyproject.toml
space_packet_parser/xtcedef.py
tests/unit/test_xtcedef.py

Changes in this PR:
- Instead of hardcoding a `XtcePacketDefinition._default_namespace`, read the namespace from the XTCE document.
- This requires the `lxml` module instead of the built-in `xml`, since the latter's `Element` does not have an `nsmap` attribute.
- Adds new `lxml` dependency to the list of requirements.
- Since `XtcePacketDefinition.__init__`'s `xtce_document` argument might be a `Path`, we need a version &ge;4.8, since [that's when support was added for `Path` objects](https://lxml.de/4.8/changes-4.8.0.html).
- Switches to `lxml` in tests as well, for consistency.

Use `lxml` instead of standard library `xml` to improve namespace identification

---

pylintrc
space_packet_parser/xtcedef.py
tests/unit/test_xtcedef.py

This PR ended up turning into a kind of rollup of several of the changes I've made in my fork to make the module usable. I am opening this as a draft for discussion purposes and as a sort of already-implemented feature(s) request. The major changes here are:
- ~Addition of a `BooleanParameterType` class~
- Implementation of byte ordering/endianness checking
- While in an ideal world, spacecraft subsystems, etc. would all stick to big endian data types, in practice that is not the case.  Hardcoding big endian types for all parameters is not a safe assumption, and the ability to handle both MSB- and LSB-first fields is a pretty fundamental/core functionality
- I noticed several notes in the code along the lines of `TODO: implement ByteOrderList to inform endianness.` I'm not sure what …

Add straightforward endianness implementation; accommodate all allowable string encodings

---

space_packet_parser/parser.py
space_packet_parser/xtcedef.py
tests/unit/test_parser.py

This enables the same call structure when parsing the data fields and easier pass-through. It is also faster in the hot-loop than using `isinstance()` to get the specific path to go down.
This builds upon the other two performance PRs as I'm whittling things down here and the calling type definitions change, so it was easier to test on top of everything. I can remove them if that would be helpful, but for review you can just look at the final commit here: 98491cec9df52926849aae7930c44b084812ec50
Changes:
* Added a `parse()` method to `SequenceContainer` and `Parameter` with the same call signature.
* (Note that this is actually the same call signature as `parse_value()`, but with different return types. I'm wondering if there is actually a way to structure these all the same...)
* Moved …

Add a Parseable Protocol and parse method

---

docs/source/changelog.md
space_packet_parser/xtcedef.py
tests/integration/test_xtce_based_parsing/test_suda_parsing.py
tests/unit/test_xtcedef.py

When dealing with binary data, users generally want the most raw data which is the bytes directly rather than a string representation of the bits. This is a breaking change and if users want to get the binary string, they can format the string output themselves now.
Brief description of changes. If you write good commit messages, put the concatenated list of messages here.

FIX: Return the raw bytes from a BinaryDataEncoding

---

space_packet_parser/xtcedef.py
tests/unit/test_xtcedef.py

This is a proof of concept PR for now, building on top of the little-endian PR to reduce the thrashing when rebasing, so only the last commit is relevant. It is currently failing one test because of the binary-bytes transition that would make this PR easier as well.
I get 5.2s with this PR, vs 6.6s from main, so a pretty significant speed-up.
The major changes are:
- Move some parameter instantiation logic up into the init routines rather than in the hot-loop reading packets.
- Make a `read_bytes` and `read_int` method on `PacketData` for the two explicit cases of wanting to get data without having to convert between the two so frequently.
- Move the if-branches from the `read()` method up into their respective data encodings so that we limit the number of checks needed when returning the …

Faster value parsing

---

docs/source/changelog.md
examples/parsing_and_plotting_idex_waveforms_from_socket.py
space_packet_parser/parser.py
space_packet_parser/xtcedef.py
tests/unit/test_csvdef.py
tests/unit/test_xtcedef.py

This combines the `PacketData` and `Packet` classes together. A `Packet` now contains all of the raw bytes, and can be "parsed" as it goes keeping track of the reading. This enables us to avoid having to pass in `parsed_data` to the parsing methods and just pass in the `Packet` container that already has that information. It would be good to look at the definition of that class and let me know what you think it should/should not contain as public/private methods (maybe we don't want to make the reads public?).
This simplifies some of the tests so we don't always have to pass in `parsed_data={}` now.
This seems to speed up the test suite pretty significantly too. I went from 15s to 7.5 s locally.

Unify packet class

---

.github/workflows/tests.yml
docker-compose.yml
docs/source/changelog.md
pyproject.toml
space_packet_parser/xtcedef.py
tests/unit/test_xtcedef.py

Bump python requirement to 3.9 and remove 3.8 tests and github workflow
Add support for MIL-1750A float parsing
Add test cases pulled from MIL-1750A standard document

Support MIL-1750A Float Encoding

---

docs/source/_static/browser-parsing.html
docs/source/browser-demo.rst
docs/source/contents.rst

This is an example of how this project can be leveraged in the browser and people can test it out themselves.
This puts the html as a sub-page under the current sphinx design rather than a separate landing page. Let me know if you want it to be completely separate, or some other name for it etc... Happy to modify this.
- [n/a] The changelog.md has been updated

DOC: Add in-browser capability

---

space_packet_parser/comparisons.py
space_packet_parser/encodings.py
space_packet_parser/parameters.py
space_packet_parser/parser.py

This makes some parameters keyword only as an alternative to skipping the linter altogether. If we go down this path, we should probably make some other parameters keyword only too and not just the ones to satisfy the linter.
closes #76

MNT: Turn some position arguments into keyword-only

---

docs/source/changelog.md
docs/source/users.md
examples/parsing_and_plotting_idex_waveforms_from_socket.py
space_packet_parser/comparisons.py
space_packet_parser/encodings.py
space_packet_parser/parameters.py
space_packet_parser/parseables.py
space_packet_parser/parser.py
tests/integration/test_bufferedreader_parsing.py
tests/integration/test_csv_based_parsing/test_ctim_parsing.py
tests/integration/test_xtce_based_parsing/test_inheritance_restrictions.py
tests/integration/test_xtce_based_parsing/test_jpss_parsing.py
tests/integration/test_xtce_based_parsing/test_suda_parsing.py
tests/unit/test_csvdef.py
tests/unit/test_parseables.py
tests/unit/test_xtcedef.py

This allows a user to index directly into the packet itself. Rather than being defined by the raw bytes.
Separate out the raw packet data from the packet object itself to keep these as two separate things.
- [n/a] Deprecated/superseded code is removed or marked with deprecation warning
- [n/a] Current dependencies have been properly specified and old dependencies removed

MNT: Make packet class be a mapping based on data items

---

space_packet_parser/definitions.py

We can avoid the `isinstance` checks in the while-loops by explicitly setting the type of read to do on the initial entry into the generator.
closes #80

Parser read method

---

.github/workflows/release.yml
CITATION.cff
README.md
docs/source/developers.md
pyproject.toml

This adds an automatic upload to PyPI when a GitHub Release is made.
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
It does require the version to already be bumped prior to making the release. So I think the recommended workflow would be to do all the tagging/versioning, then push to GitHub, then make a GitHub Release from that tag/commit. I automate all of those steps as well to pull the version from the tag, but I Poetry doesn't work as well with that style so I'm not sure what the recommended approach is with Poetry so I opted for manual for now and someone else can look into automating the poetry version bump.

REL/CI: Automate release workflow

---

docs/source/changelog.md
pyproject.toml
space_packet_parser/encodings.py
space_packet_parser/packets.py
tests/unit/test_xtcedef.py

Fix incorrect parsing of StringDataEncoding XML elements and resulting parsing bugs for parsing strings themselves
Return bytes objects for raw strings and str objects for derived values.

Fix Incorrect String Parsing

---

docs/source/changelog.md
space_packet_parser/comparisons.py
space_packet_parser/definitions.py
space_packet_parser/encodings.py
space_packet_parser/packets.py
space_packet_parser/parameters.py
tests/integration/test_xtce_based_parsing/test_jpss_parsing.py
tests/unit/test_packets.py
tests/unit/test_xtcedef.py

This adds the ability to subclass the built-in types and return an item that can be acted upon directly rather than having to access `parsed_item.raw_value` as an attribute to do any work with the item.
The built-in types are immutable and can't have attributes added to them so we inject the `raw_value` attribute in the new constructor of each explicit type.
**this PR**
```
{'VERSION': 0, 'TYPE': 0, 'SEC_HDR_FLG': 1, 'PKT_APID': 1424, 'SEQ_FLGS': 3, 'SRC_SEQ_CTR': 77, 'PKT_LEN': 1065, 'SHCOARSE': 1343, 'SHFINE': 19201, ...
```
**main**
```
{'VERSION': ParsedDataItem(name='VERSION', raw_value=0, unit=None, derived_value=0, short_description=None, long_description=None), 'TYPE': ParsedDataItem(name='TYPE', raw_value=0, unit=None, derived_value=0, short_description=None, …
```

MNT: Use built-in types for return data objects

---

.github/workflows/release.yml
CITATION.cff
docs/source/developers.md
pyproject.toml

Change the release process slightly. This cleans up a lot and does better checking on the tags to ensure release are created correctly. 

Improve Release CI Pipeline

---

space_packet_parser/parameters.py
tests/unit/test_xtcedef.py

This gives the ability to get back to the raw value if desired still, but returns what was used for the "lookup" / bool conversion as that is likely what a user needs for the first debug step. Then they can get to the raw-raw value themselves if they really need it.
closees #93

MNT: Change to returning intermediate values for enumerated and booean parameters

---

CITATION.cff
docs/source/changelog.md
pyproject.toml
space_packet_parser/packets.py
space_packet_parser/parameters.py
tests/unit/test_xtcedef.py

Force Boolean and Enumerated parameter parsing to key off of the raw encoded value, per XTCE spec

Fix bug in representing falsy raw value in parsed _Parameters

---

space_packet_parser/definitions.py

The parameter types and parameters can be read through once and loaded into a cache straight away and then the lookups done on the cache after that. This prevents a findall() call iterating through the entire XML document every time a new parameter is found.
Profiling with the script provided in #112, we go from 12s to 0.03s for the Definition creation.
closes #112

PERF: Reduce number of times findall is called on XML file

---

docs/source/changelog.md
pyproject.toml
space_packet_parser/calibrators.py
space_packet_parser/definitions.py
space_packet_parser/encodings.py
space_packet_parser/parameters.py
tests/integration/test_xtce_based_parsing/test_ctim_parsing.py
tests/unit/test_xtcedef.py

- Emit UserWarning for more visible issues with XTCE definitions.
- Filter out warnings emitted by the tests that aren't of interest to the tests themselves. Fix some element tree comparisons that had future warnings indicating an explicit check against "is None" was needed. (There are now zero warnings when running pytest)
- Use the walrus operator for assignment to avoid duplicate lookups with element tree find calls. (There are probably more places that this could be helpful, but I just fixed the places with warnings)
closes #116

MNT: Change logger warning to UserWarning and ignore some inconsequential test warnings

---

docs/source/changelog.md
space_packet_parser/definitions.py
space_packet_parser/encodings.py
space_packet_parser/exceptions.py
space_packet_parser/packets.py
space_packet_parser/parameters.py
tests/unit/test_packets.py

This refactors out the reading of a byte-stream into a separate generator function that can yield raw CCSDSPackets with only the raw bytes. The definitions and parsing logic can use this generator to yield packets and then parse whatever they need to after the fact. This enables someone to use this generator without a packet definition and to investigate what is in the packet stream without needing to know more detailed information about how individual packets are laid out internally.
closes #81
closes #104

MNT/ENH: Add a raw CCSDS packet generator

---

docs/source/changelog.md
space_packet_parser/definitions.py
tests/unit/test_packets.py

This builds on the packet refactor work (the final commit of this PR is relevant to continuation packets) and adds continuation packet support to the XTCE parsing and packet generation. This adds logic to concatenate packet data fields together across successive packets (if there was too much data to fit in a single CCSDS packet or it was logically better to split by other teams).
- Add warnings if packets are out of sequence within a given apid.
- Add ability to remove secondary header bytes from subsequent packets.
``definition.packet_generator(data, combine_segmented_packets=True, secondary_header_bytes=4)``
Notes:
- This is only in the XTCE packet parsing definition generator for now, so thoughts on doing this up a level are welcome. I chose not to to keep it as "raw" as possible at …

Add continuation packet support

---

docs/source/changelog.md
pyproject.toml
space_packet_parser/cli.py
space_packet_parser/comparisons.py
space_packet_parser/definitions.py
space_packet_parser/packets.py
tests/integration/test_cli.py

This adds a very basic command line interface and prints the header contents of a file to the terminal. I figured this would be easier to discuss as a prototype rather than opening an issue.
I've currently implemented this with just basic built-in argparse utilities, but I'm wondering if we should add some other dependencies to make the cli a little nicer? The two that have caught my eye are:
* Rich: https://github.com/Textualize/rich for color/formatting
* Click: https://github.com/pallets/click for a decorator based approach to defining the cli in a cleaner manner.
I don't keep up with all of the cli/formatting libraries, so if there are others I should look at let me know. These libraries don't have any other dependencies which is nice as well, so they would each only add their …

Add a command line interface

---

.github/workflows/pr_tests.yml
docs/source/changelog.md
pyproject.toml
space_packet_parser/definitions.py
space_packet_parser/packets.py
space_packet_parser/xarr.py
tests/integration/test_xarr.py
tests/test_data/ctim/ctim_xtce_v1.xml

This is a first stab at a working implementation based on the IMAP code. I removed anything that was particular to IMAP, including the time dimension.

Modify IMAP code to create generic xarray dataset from packet data file

---

.github/workflows/pr_tests.yml
.gitignore
space_packet_parser/packets.py
tests/integration/test_socket_parsing.py

I think you need to enable codecov (or some other external service if you prefer) for this to work as I couldn't find a way to enable this. Maybe this is impetus to move to the LASP org so we can both admin things?
https://app.codecov.io/gh
On IMAP we use a token, but I don't think that is required anymore and it would be nice if we can get OIDC to work instead.
https://github.com/IMAP-Science-Operations-Center/imap_processing/blob/693fbdfffd12fa3ec9249f2d5f03fbee39ae5039/.github/workflows/test.yml#L54-L57
I can add a badge once the coverage link/report is enabled.
- [n/a] The changelog.md has been updated

CI: Add code coverage reports to external source

---

.github/workflows/pr_tests.yml

Trying to see if this passes the proper url/handshake to codecov's OIDC.

CI: Add id-token write permissions for codecov OIDC

---

docs/source/changelog.md
space_packet_parser/encodings.py
tests/test_data/ctim/ctim_xtce_v1.xml
tests/test_data/jpss/contrived_inheritance_structure.xml
tests/test_data/jpss/jpss1_geolocation_xtce_v1.xml
tests/test_data/test_xtce.xml
tests/unit/test_xtcedef.py

- N/A
This PR resolves the issue I raised in my comment [here](https://github.com/medley56/space_packet_parser/pull/68#discussion_r1942092917).

BUGFIX: update allowed float encodings to match XTCE standard

---

.github/workflows/tests.yml
.gitignore
docs/source/benchmarking.md
docs/source/changelog.md
docs/source/contents.rst
examples/parsing_and_plotting_idex_waveforms_from_socket.py
pyproject.toml
tests/benchmark/test_benchmarks.py
tests/benchmark/test_fast_benchmarks.py
tests/benchmark/test_slow_benchmarks.py
tests/conftest.py

This PR adds benchmark tests using `pytest-benchmark`. The benchmark tests are included in the `tests/benchmark` directory and are run as part of the normal test suite.

Add benchmarking to test suite

---

docs/source/changelog.md
space_packet_parser/common.py
space_packet_parser/packets.py
space_packet_parser/xtce/encodings.py
space_packet_parser/xtce/parameter_types.py
tests/unit/test_xtce/test_calibrators.py
tests/unit/test_xtce/test_comparisons.py
tests/unit/test_xtce/test_parameters.py

They are not related to packets directly and are used in several different modules for parsing. They could probably go in parameter_types, but that could potentially lead to confusion about whether it is an XTCE StringParameterType or a data value of StrParameter. The generic place is in common, since these are really subclasses of builtins.

MNT: Move parameter data types to common module

---

docs/source/changelog.md
space_packet_parser/cli.py
space_packet_parser/common.py
space_packet_parser/xtce/calibrators.py
space_packet_parser/xtce/comparisons.py
space_packet_parser/xtce/containers.py
space_packet_parser/xtce/definitions.py
space_packet_parser/xtce/encodings.py
space_packet_parser/xtce/parameter_types.py
space_packet_parser/xtce/parameters.py
tests/benchmark/test_xtce_parsing_benchmarks.py
tests/integration/test_xtce_based_parsing/test_inheritance_restrictions.py
tests/test_data/idex/idex_combined_science_definition.xml
tests/test_data/jpss/contrived_inheritance_structure.xml
tests/test_data/suda/suda_combined_science_definition.xml
tests/unit/test_xtce/test_definitions.py

Modify the parsing of XTCE documents to ensure that SequenceContainer objects are kept unique and reused instead of parsed and stored multiple times.
This PR adds checks to the parsing of ParameterSet, ParemeterTypeSet, and ContainerSet to ensure that the objects we parse out of those elements are uniquely represented in the resulting definition object. We also issue warnings for parameters and parameter types that are defined but not used.

Ensure uniqueness of parsed SequenceContainer objects

---

.github/workflows/tests.yml

This runs all of the pre-commit checks, not just the ruff command explicitly.

CI: Run pre-commit and not just ruff

---

.github/workflows/tests.yml
.pre-commit-config.yaml
.readthedocs.yml

The current merge to main failed because it ran "no commit to a branch named main". I enabled pre-commit.ci service so that will do the linting checks for us now as a separate action. (we could remove that check to fix this too)

CI: Remove explicit linting job and use precommit.ci instead

---

.github/workflows/tests.yml
docs/source/changelog.md
examples/csv_to_xtce_conversion.py
space_packet_parser/common.py
space_packet_parser/xtce/__init__.py
space_packet_parser/xtce/calibrators.py
space_packet_parser/xtce/comparisons.py
space_packet_parser/xtce/containers.py
space_packet_parser/xtce/definitions.py
space_packet_parser/xtce/encodings.py
space_packet_parser/xtce/parameter_types.py
space_packet_parser/xtce/parameters.py
tests/conftest.py
tests/test_data/test_xtce.xml
tests/test_data/test_xtce_default_namespace.xml
tests/test_data/test_xtce_no_namespace.xml
tests/unit/test_xtce/test_calibrators.py
tests/unit/test_xtce/test_comparisons.py
tests/unit/test_xtce/test_definitions.py
tests/unit/test_xtce/test_encodings.py
tests/unit/test_xtce/test_parameter_types.py
tests/unit/test_xtce/test_parameters.py

- Avoid passing namespace dicts down through all from_xml methods in favor of predefining a custom Element class that contains the namespace
- Convert internal parameter types, parameters, and containers to set objects with read only dict accessor properties.
- Increase performance by minimizing broad XML find and findall calls.

Handle all namespace cases - default, prefixed, no namespace.

---

space_packet_parser/__init__.py
space_packet_parser/definitions.py
tests/benchmark/test_xtce_parsing_benchmarks.py
tests/unit/test_xtce/test_definitions.py

When I was trying to profile things across versions, it got a little annoying to comment/uncomment lines of files for the different loading XTCE patterns. This adds a small shim layer for the old `XtcePacketDefinition` format that then warns and suggests how to transition to the new patterns, still working the same as previously.

MNT: Add backcompat shim to ease transition to new packet file loading

---

space_packet_parser/packets.py

int.from_bytes() is about 2x slower than a direct bitshift of two values, and we avoid some other checks as well.
```
python -m timeit "b=b'\x01\x02\x03\x04\x05\x06'*100; int.from_bytes(b[-2:], 'big')" 
5000000 loops, best of 5: 80.2 nsec per loop
python -m timeit "b=b'\x01\x02\x03\x04\x05\x06'*100; (b[-2] << 8) | b[-1]"
5000000 loops, best of 5: 47.8 nsec per loop
```

PERF: Use direct bitshift logic instead of _extract_bits function

---

space_packet_parser/xtce/encodings.py

LinearAdjusters are only ever intended to scale integers. This error is raised if that value is not an int for some reason. It's unlikely but this error message is preferable to just forcing integer math, which may create very confusing parsing bugs.

Improve error message for float returned from LinearAdjuster

---

space_packet_parser/xarr.py
space_packet_parser/xtce/comparisons.py
space_packet_parser/xtce/definitions.py
space_packet_parser/xtce/encodings.py
tests/unit/test_packets.py
tests/unit/test_xarr.py
tests/unit/test_xtce/test_comparisons.py
tests/unit/test_xtce/test_encodings.py

I noticed that we had low-ish coverage on a couple modules, mostly on the error-handling since most of the tests are run correctly. I found some locations where we were checking for exception cases in `evaluate` methods when we should have been pre-checking in either init or `from_xml`. 
I added some additional coverage to the packets.py module but I'm thinking that will probably need rework after @greglucas 's refactoring in #140 

Improve unit test coverage

---

.devcontainer/CLAUDE.md
.devcontainer/devcontainer.json
.devcontainer/setup-dev-environment.sh
.gitignore
docs/source/_static/pyodide_parse_packets.js
docs/source/changelog.md
docs/source/users.md
examples/csv_to_xtce_conversion.py
examples/parsing_and_plotting_idex_waveforms_from_socket.py
space_packet_parser/__init__.py
space_packet_parser/ccsds.py
space_packet_parser/cli.py
space_packet_parser/xarr.py
space_packet_parser/xtce/containers.py
space_packet_parser/xtce/definitions.py
tests/benchmark/test_slow_benchmarks.py
tests/integration/test_bufferedreader_parsing.py
tests/integration/test_socket_parsing.py
tests/integration/test_xarr.py
tests/integration/test_xtce_based_parsing/test_ctim_parsing.py
tests/integration/test_xtce_based_parsing/test_inheritance_restrictions.py
tests/integration/test_xtce_based_parsing/test_jpss_parsing.py
tests/integration/test_xtce_based_parsing/test_suda_parsing.py
tests/unit/test_ccsds.py
tests/unit/test_xarr.py
tests/unit/test_xtce/test_containers.py
tests/unit/test_xtce/test_definitions.py

This PR removes the intermediate API on `XtcePacketDefinition.packet_generator` and cleans up the implementation of `xarr.create_dataset` to handle separate kwarg dicts for the `ccsds_generator` and the `parse_bytes` method. The `create_dataset` function will never be allowed to parse packets with incorrect length though because such behavior will not permit construction of the resulting `DataSet` object.

Bring your own bytes generator

---

.devcontainer/Dockerfile
.devcontainer/claude-settings.json
.devcontainer/devcontainer.json
.gitignore
.pre-commit-config.yaml
codecov.yml
docs/source/changelog.md
docs/source/users.md
pyproject.toml
space_packet_parser/__init__.py
space_packet_parser/cli.py
space_packet_parser/xtce/__init__.py
space_packet_parser/xtce/definitions.py
space_packet_parser/xtce/validation.py
tests/conftest.py
tests/integration/test_cli.py
tests/test_data/SpaceSystem.xsd
tests/test_data/ctim/ctim_xtce_v1.xml
tests/test_data/idex/idex_combined_science_definition.xml
tests/test_data/jpss/contrived_inheritance_structure.xml
tests/test_data/jpss/jpss1_geolocation_xtce_v1.xml
tests/test_data/suda/suda_combined_science_definition.xml
tests/test_data/test_xtce_4byte.xml
tests/test_data/test_xtce_no_namespace.xml
tests/unit/test_xtce/test_definitions.py
tests/unit/test_xtce/test_validation.py

This PR implements comprehensive XTCE document validation capabilities for Space
Packet Parser, adding both XSD schema validation and structural validation to help
ensure XTCE documents are correct and will work properly for parsing packets.
- **Added `space_packet_parser/xtce/validation.py`** (441 lines) - Complete
validation system with:
- `ValidationLevel` enum (schema, structure, all)
- `ValidationError` and `ValidationResult` dataclasses for structured error
reporting
- `validate_xtce()` function as main entry point
- Schema validation against XSD with automatic schema downloading
- Structural validation for XTCE-specific business rules
- Reference integrity checking (Parameters, ParameterTypes, Containers)
- **Updated `space_packet_parser/__init__.py`** - Exported `validate_xtce` …

129 add a schema validator checker

---

examples/csv_to_xtce_conversion.py
examples/parsing_and_plotting_idex_waveforms_from_socket.py
space_packet_parser/__init__.py
space_packet_parser/cli.py
space_packet_parser/common.py
space_packet_parser/generators/__init__.py
space_packet_parser/generators/ccsds.py
space_packet_parser/generators/fixed_length.py
space_packet_parser/generators/utils.py
space_packet_parser/packets.py
space_packet_parser/xarr.py
space_packet_parser/xtce/definitions.py
tests/benchmark/test_slow_benchmarks.py
tests/integration/test_bufferedreader_parsing.py
tests/integration/test_socket_parsing.py
tests/integration/test_xtce_based_parsing/test_ctim_parsing.py
tests/integration/test_xtce_based_parsing/test_inheritance_restrictions.py
tests/integration/test_xtce_based_parsing/test_jpss_parsing.py
tests/integration/test_xtce_based_parsing/test_suda_parsing.py
tests/unit/test_generators/test_ccsds.py
tests/unit/test_generators/test_fixed_length.py
tests/unit/test_generators/test_utils.py
tests/unit/test_xarr.py
tests/unit/test_xtce/test_containers.py
tests/unit/test_xtce/test_definitions.py

Enhanced the `create_dataset` function to accept file-like objects (such as those created with `open(filepath, "rb")` or `io.BytesIO`)
in addition to file paths for both packet files and XTCE definitions.
- **Enhanced type annotations**: Updated `packet_files` parameter to accept `BinaryIO` and `bytes` types alongside existing `str` and
`Path` types
- **Added file-like object detection**: Implemented logic to differentiate between file paths and file-like objects using type checking
- **Restructured packet processing**: Refactored the main loop to handle both file paths (opened with context manager) and file-like
objects (used directly)
- **Improved code organization**: Extracted packet processing logic into a helper function `_process_generator()` to avoid code
duplication
- **File-like …

Add support for filelike objects in create_dataset
