.github/workflows/tests.yml, CHANGES.md, docs/source/users.md, pyproject.toml, space_packet_parser/parser.py
Documentation of example usage has been updated with proper "rb" mode.
Exception handling has been added in the event that a file is opened in non-binary mode.
=> Add error handling to the textio error

CITATION.cff, docs/source/changelog.md, docs/source/developers.md, pyproject.toml
Update CITATION.cff
Update changelog.md
Bump version in pyproject.toml
Minor update to developers.md documentation
=> Release v4.1.0

.github/workflows/tests.yml, docker-compose.yml, docs/source/changelog.md, pyproject.toml
Add Greg as an author
Add a 3.12 docker compose test
=> Release branch for 4.1.1

space_packet_parser/parser.py
Previously the buffer was trimmed after every packet parsed. Now we only trim every 20 MB read.
* Would we want to make the 20 MB user controllable via keyword argument? (I just arbitrarily chose that value)
* Question for the future: Would we want to default to reading the entire files / draining the sockets now? It would probably be good to make the file read size larger than 4096 so there aren't as many appends happening, but we also might not want to read an entire file into memory, so perhaps there is a sweet spot for the default.
Here is an example that is helped by this. I'm not sure there is a great test we can add, but open to thoughts/ideas on that. I think the problem in this case is that we read everything into a large BitStream and then keep trimming the front of the array …
=> PERF: Reduce number of buffer resize operations

docs/source/changelog.md, space_packet_parser/xtcedef.py, tests/unit/test_xtcedef.py
Brief description of changes. If you write good commit messages, put the concatenated list of messages here.
=> Allow using a BooleanExpression inside a ContextCalibrator element.

README.md, docs/source/index.rst
This is related to items in this issue #36.
- Added logos of IMAP and CLARREO mission.
=> added IMAP and CLARREO to docs and readme

space_packet_parser/parser.py
This code block is already identified above, so rely on it there rather than reimplementing the same logic twice.
The only difference is the elif -> else, but I don't think there are any other routes, so the else should save us an isinstance check as well.
- [n/a] The changelog.md has been updated
=> MNT: re-use external function in parser loop

README.md, docs/source/conf.py, docs/source/contents.rst, docs/source/index.rst, docs/source/users.md
- Include README in readthedocs front page
- Add Libera and CTIM logos to missions list
- Add DOI badge to README
=> Documentation changes

.readthedocs.yml, docs/source/developers.md, pyproject.toml
Remove restrictions on dev dependencies
Fix readthedocs build
=> Fix Doc Build

space_packet_parser/xtcedef.py
This does a string index lookup for the termination character instead of needing to track everything through the while loop and hitting the `packet_data.peek()` method multiple times. This is a refactor and doesn't address the other items of string parsing needing to be updated.
Note, I'm still a bit unclear about all of the various cases for handling termination character even though I've read the spec a few times now... Some more full examples would definitely help. Going off of this example: https://github.com/yamcs/yamcs/blame/78b9553caf3c9f7ef7a6e6897d236a69aeed8190/yamcs-core/src/test/resources/xtce/strings-tm.xml#L37-L53
I'm actually wondering if when using the termination character as the delimiter you still need to include a maxSizeBits value through the Variable Element?
xref: …
=> MNT: Simplify the string parsing termination character handling

docs/source/_static/browser-parsing.html, space_packet_parser/parameters.py
- Updates for HTML parsing example for new 5.0 release
- Updates for Parameter type warnings
=> DOC: Minor updates to documentation

.github/issue_template.md, .github/pull_request_template.md, CITATION.cff, README.md, docs/source/changelog.md, pyproject.toml
- Update version metadata and changelog
- Remove transition from top of README.md
=> Prepare for Release of 5.0.0

.github/workflows/release.yml
=> Fix bug in release pipeline prerelease regex

docs/source/changelog.md, space_packet_parser/definitions.py
=> BUGFIX: fix kbps calculation for generator when show_progress=True

CITATION.cff, pyproject.toml
=> Prep for 5.1.0rc1 release

.github/workflows/tests.yml
- Rename workflow file to tests since they are more than just PR tests now
=> Add workflow to run tests on any change to main and also daily on main

.github/workflows/tests.yml, pyproject.toml
=> MNT: Add extras groups for easier installation of optional packages

CITATION.cff, README.md, pyproject.toml
- Remove references to old GitHub repo path
- Add PyHC reference
- Update IMAP image link
=> Minor tweaks to readme and metadata

.github/workflows/tests.yml
Trying this again now that we have successful codecov on main to see if that helps.
=> CI: Try codecov with OIDC and avoid tokens

docs/source/developers.md, pyproject.toml
Just a few small changes I made while reading through the repo
=> Tiny fixes found during other work

docs/source/changelog.md, docs/source/users.md, space_packet_parser/__init__.py, space_packet_parser/definitions.py, tests/unit/test_space_packet_parser.py
=> Rename load_xml to load_xtce for consistency

.devcontainer/CLAUDE.md, .devcontainer/Dockerfile, .devcontainer/claude-settings.json, .devcontainer/devcontainer.json, .devcontainer/init-firewall.sh, .dockerignore
This is purely for development. Adding a devcontainer that comes with Claude Code preinstalled to allow developers to easily use the agentic form of Claude to assist with development.
=> Add devcontainer configuration

.devcontainer/devcontainer.json, .devcontainer/setup-git-signing.sh
Add automatic setup of commit signing from inside devcontainer based on host ~/.gitconfig
=> Add automatic commit signing setup

space_packet_parser/xtce/definitions.py, tests/unit/test_xtce/test_definitions.py
=> MNT: Add better error message for XTCE from file-like
